server:
  port: 8081
keycloak:
  server_url: ${SERVER_URL:http://localhost:8080}
  client_id: ${CLIENT_ID:admin-cli}
  client_secret: ${CLIENT_SECRET:Lszl3UnHv8NtlNd0HSPOqvIKtYY2madP}
  username: ${USERNAME_KC:admin}
  password: ${PASSWORD:admin}
  realm: ${REALM:comarkapp}
  issuer: ${ISSUER:http://14d67312e708.ngrok.app/realms/comarkapp}
  realm_master: ${realm_master:master}
spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: b9d79b313155f4
    password: a1498c62918e91
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: ComarkService
  r2dbc:
    url: ${DB_HOST:r2dbc:postgresql://localhost:5432/comarkapp}
    username: ${DB_HOST:postgres}
    password: ${DB_HOST:test}
    pool:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/comarkapp
          jwk-set-uri: http://localhost:8080/realms/comarkapp/protocol/openid-connect/certs
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.data.r2dbc.core: DEBUG
    org.keycloak: DEBUG
    io.r2dbc.postgresql: DEBUG
    org.springframework.security: DEBUG

---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    properties:
      dialect: postgres
    url: r2dbc:tc:postgresql:///test?TC_IMAGE_TAG=9.6.8
    username: test
    password: test

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.data.r2dbc.core: DEBUG
    org.keycloak: DEBUG
    io.r2dbc.postgresql: DEBUG
    org.springframework.security: DEBUG

